site_name: Colight
site_url: https://colight.dev
repo_url: https://github.com/colight-dev/colight
repo_name: colight-dev/colight
edit_uri: tree/docs/docs/
watch:
  - mkdocs.yml
  - docs
theme:
  name: material
  custom_dir: docs/overrides
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil-box
    download: material/download
  palette:
    primary: white
    accent: custom
  font:
    text: Crimson Pro
  features:
    - navigation.indexes
    - toc.integrate
    - content.action.edit
  logo: false
nav:
  - Home: index.md
  - Essential Reading: essential-reading
  - Scene3d: scene3d.py
  - Guides:
      - Getting Started: guides/getting-started.colight
      - Data Analysis Workflow: guides/data-analysis-workflow.colight
      - Responsive Dashboards: guides/responsive-dashboards.colight
  - The Basics:
      - Layouts: system-guide/layouts
      - State: system-guide/state
      - HTML with Hiccup: system-guide/html-with-hiccup
      - Color: learn-more/color
      - JS Imports: system-guide/js-imports
      - Interactivity & Animation:
          - Sliders: interactivity/sliders.colight
          - Animating Frames: interactivity/frames
          - Mouse events: interactivity/events
          - Conditional Rendering: learn-more/cond
          - Tailing data: interactivity/tail
  - Export:
      - Save to File: export/save_to_file
      - Images and Video: export/images_and_video
  - Advanced:
      - Python Event Loops: learn-more/python-event-loop
      - Compare with Observable Plot: learn-more/vs-observable
      - Plot Options: learn-more/plot-options
  - Examples:
      - Draw Density: examples/draw-density
      - Live Editing Source Code: examples/live-edit-source
      - Ellipse Mark: examples/ellipse-mark
      - Histogram Mark: examples/histogram-mark
      - Image Mark: examples/image-mark
      - Timelines with barX: examples/barx-timeline
      - Highlighting Code: examples/bylight
      - Rendering LaTeX: examples/katex
      - Render Pixel Data: examples/pixels
  - API Docs:
      - Plot: api/plot
      - Scene3D: api/scene3d
  - How Do I...: learn-more/how-do-i

  - Changelog: CHANGELOG.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
plugins:
  - search
  - colight.docs.api_plugin:
      modules:
        - module: colight.plot
          output: api/plot.md
        - module: colight.scene3d
          output: api/scene3d.md
  - colight.docs.site_plugin:
      verbose: true
      format: markdown
      include: ["*.py", "*.colight.py"]
      ignore: ["llms.py", "data.py", "__init__.py"]
      file_options:
        "*.py":
          hide_statements: true
  - mkdocs-jupyter:
      include: ["*.pyXXXXX"]
      ignore: ["llms.py", "*.colight.py"]
      execute: true
      allow_errors: false
      kernel_name: python3
      include_requirejs: true
      include_source: True
      remove_tag_config:
        remove_cell_tags:
          - hide
        remove_input_tags:
          - hide_source
        remove_all_outputs_tags:
          - hide_output
extra_css:
  - stylesheets/custom.css
  - stylesheets/bylight.css
extra_javascript:
  - js/dist/embed.js
  - js/bylight.js
  - js/scroll-fix.js
  - js/command-k.js
  - js/colight-loader.js
hooks: []
# Temporarily disabled hooks due to path issues
# - packages/colight/src/colight/scripts/css_modifier.py
# - packages/colight/src/colight/scripts/tailwind_builder.py
