site_name: Colight
site_url: https://colight.dev
repo_url: https://github.com/colight-dev/colight
repo_name: colight-dev/colight
docs_dir: packages/colight-docs/src/colight_docs
watch:
  - mkdocs.yml
  - packages/colight-docs/src/colight_docs
theme:
  name: material
  custom_dir: packages/colight-docs/src/colight_docs/overrides
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil-box
    download: material/download
  palette:
    primary: white
    accent: custom
  font:
    text: Crimson Pro
  features:
    - navigation.indexes
    - toc.integrate
    - content.action.edit
  logo: false
nav:
  - Home: index.md
  - Essential Reading: essential-reading.py
  - Scene3d: scene3d.py
  - Guides:
      - Getting Started: guides/getting-started.py
      - Data Analysis Workflow: guides/data-analysis-workflow.py
      - Responsive Dashboards: guides/responsive-dashboards.py
  - The Basics:
      - Layouts: system-guide/layouts.py
      - State: system-guide/state.py
      - HTML with Hiccup: system-guide/html-with-hiccup.py
      - Color: learn-more/color.py
      - JS Imports: system-guide/js-imports.py
      - Interactivity & Animation:
          - Sliders: interactivity/sliders.py
          - Animating Frames: interactivity/frames.py
          - Mouse events: interactivity/events.py
          - Conditional Rendering: learn-more/cond.py
          - Tailing data: interactivity/tail.py
  - Export:
      - Save to File: export/save_to_file.py
      - Images and Video: export/images_and_video.py
  - Advanced:
      - Python Event Loops: learn-more/python-event-loop.py
      - Compare with Observable Plot: learn-more/vs-observable.py
      - Plot Options: learn-more/plot-options.py
  - Examples:
      - Draw Density: examples/draw-density.py
      - Live Editing Source Code: examples/live-edit-source.py
      - Ellipse Mark: examples/ellipse-mark.py
      - Histogram Mark: examples/histogram-mark.py
      - Image Mark: examples/image-mark.py
      - Timelines with barX: examples/barx-timeline.py
      - Highlighting Code: examples/bylight.py
      - Rendering LaTeX: examples/katex.py
      - Render Pixel Data: examples/pixels.py
  - API Docs:
      - Plot: api/plot.md
      - Scene3D: api/scene3d.md
  - How Do I...: learn-more/how-do-i.py

  - Changelog: CHANGELOG.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
plugins:
  - search
  - colight.mkdocs.api_plugin:
      modules:
        - module: colight.plot
          output: api/plot.md
        - module: colight.scene3d
          output: api/scene3d.md
  - colight.mkdocs.site_plugin:
      verbose: false
      format: markdown
      include: ["*.py", "*.colight.py"]
      ignore: ["llms.py", "data.py", "__init__.py"]
      file_options:
        "*.py":
          hide_statements: true
extra_css:
  - stylesheets/custom.css
  - stylesheets/bylight.css
extra_javascript:
  - js/dist/embed.js
  - js/bylight.js
  - js/scroll-fix.js
  - js/command-k.js
  - js/colight-loader.js
hooks: []
# Temporarily disabled hooks due to path issues
# - packages/colight/src/colight/scripts/css_modifier.py
# - packages/colight/src/colight/scripts/tailwind_builder.py
