[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"

[project]
name = "colight-site"
version = "2025.4.1"
description = "Static site generator for Colight visualizations"
authors = [
    { name = "Matthew Huebert", email = "me@matt.is" },
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "libcst>=1.4",
    "click>=8.1",
    "watchfiles>=0.21.0",
    "colight",
    "markdown>=3.5",
    "websockets>=12.0",
    "werkzeug>=3.1.3",
]

[project.license]
text = "MIT"

[project.scripts]
colight-site = "colight_cli:main"

[dependency-groups]
dev = [
    "pytest>=8.4.0",
    "pytest-asyncio>=0.21.0",
]

[tool.hatch.build.targets.wheel]
packages = [
    "src/colight_site",
    "src/colight_live",
    "src/colight_cli.py",
]

[tool.pyright]
venvPath = "../.."
venv = ".venv"
include = [
    "src",
    "tests",
]
typeCheckingMode = "standard"
reportUnusedExpression = false
reportFunctionMemberAccess = false

[tool.pytest.ini_options]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
testpaths = ["tests"]
# Ignore .py files which are not test files
addopts = "--ignore=tests/examples/"

[tool.ruff.lint]
ignore = [
    "E402",
    "F841",
]
